# Generated by Django 3.0.6 on 2020-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lairAdmin', '0002_auto_20200603_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(default='defaultCover.png', upload_to=''),
        ),
    ]
